name = "Edge of Existence"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6a35dcca818912a27ad44effe733437d5a543878997410f3fd972b4c767e742"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
